apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: faces-rollout
  namespace: faces
spec:
  replicas: 5
  strategy:
    canary:
      canaryService: faces-rollout-canary
      stableService: faces-rollout-stable
      plugins:
          argoproj-labs/gatewayAPI:
            httpRoute: argo-rollouts-http-route # our created httproute
            namespace: test
      steps:
        - setWeight: 30
        - pause: {}
        - setWeight: 40
        - pause: { duration: 15 }
        - setWeight: 60
        - pause: { duration: 15 }
        - setWeight: 80
        - pause: { duration: 15 }
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: faces-rollout
  template:
    metadata:
      annotations:
          linkerd.io/inject: enabled
      labels:
        app: faces-rollout
    spec:
      containers:
      - name: faces-rollout
        image: dwflynn/faces-service:0.8.0
        ports:
        - containerPort: 9898
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m