apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: emissary
  namespace: argocd
spec:
  destination:
    namespace: emissary
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://github.com/kflynn/Argo-Linkerd-Demo.git
      path: emissary/emissary-app
      targetRevision: HEAD
    - repoURL: https://app.getambassador.io
      chart: emissary-ingress
      targetRevision: 8.8.2
